################################################################################
# Program: Simulation_2013_11_05
# Project: Boucher Senior Thesis
# Description: Conduct a preliminary simulation study for CLS ordering vs SIS
#
# Author: Kimberly Boucher
# Date: 22 Oct 2013
#
# Notes:

################################################################################

library(Matrix)

source("C:\\Users\\boucheka\\Documents\\Thesis\\Simulation_2013_11_05_functions.R")
source("C:\\Users\\boucheka\\Documents\\Thesis\\RandomNormal.R")

# set.seed(20131105)
initialize_values()

e<-c(data=rnorm(n, mean=0, sd=1))
X<-rmvnorm(n, mu=rep(0,p), Sigma=varcov)
beta<-rep(0,p)
y<-e+X%*%beta
beta_hat <- CLS(y=y, X=X)

for(j in 1:m) {
  e<-c(data=rnorm(n, mean=0, sd=1)) # needs different variance when response depends on predictors
  #  X<-matrix(data=rnorm(n*p, mean=0, sd=1), nrow=n, ncol=p)
  #  X<-abs(matrix(data=rnorm(n*p, mean=0, sd=1), nrow=n, ncol=p)) 
  # useful for distance measure, since that is just abs of pearson corr coeff when all normal
  X<-rmvnorm(n, mu=rep(0,p), Sigma=varcov)
  # highly correlated predictors, compound symmetric aka equicorrelated generated by multivariate normal
  beta<-rep(0,p)
  y<-e+X%*%beta # just noise
  corr[,j]<-cor(y,X)
}

maxes <- apply(abs(corr), 2, max)
plot(density(maxes))

meds <- apply(abs(corr), 2, median)
#plot(density(meds))



